name: CI
 
on:
  push:
    branches: ["monorepo", "main"]
  pull_request: null
 
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: '${{ matrix.os }}'
    env:
     TARGET: ${{ matrix.target }}
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ vars.TURBO_TEAM }}
 
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Pnpm environment
        uses: pnpm/action-setup@v3
        with:
          version: 8
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install

      - name: Install Rust build target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build
        shell: bash
        run: pnpm build:prod
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
         name: ${{ matrix.target }}
         path: apps/server/target/${{ matrix.target }}/release/trunky-overlay${{ matrix.suffix }}
